using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WorkBC.Data.Model.JobBoard
{
    public class Impersonation
    {
        [Key]
        [StringLength(200)]
        public string Token { get; set; } // generated by RNGCryptoServiceProvider 

        [ForeignKey("JobSeeker")]
        public string AspNetUserId { get; set; }

        public virtual JobSeeker JobSeeker { get; set; }

        [ForeignKey("AdminUser")]
        public int AdminUserId { get; set; }

        public virtual AdminUser AdminUser { get; set; }

        // a token will work for up to 60 seconds from the time it is generated
        public DateTime DateTokenCreated { get; set; }
    }
}