<?php

namespace Tests\Feature\Auth;

use App\Auth\LegacyHashVerificationResult;
use App\Auth\LegacyPasswordHasher;
use App\Models\Enums\AccountStatus;
use App\Models\JobSeeker;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Password;
use Illuminate\Support\Facades\Schema;
use Tests\TestCase;

class JobSeekerSessionAuthTest extends TestCase
{
    /** @var array<string, string> */
    private array $vectors;

    protected function setUp(): void
    {
        parent::setUp();

        $this->vectors = json_decode((string) file_get_contents(base_path('tests/Fixtures/Auth/legacy-password-vectors.json')), true, 512, JSON_THROW_ON_ERROR);

        $this->createFixture();
    }

    protected function tearDown(): void
    {
        Carbon::setTestNow();
        $this->dropFixture();
        parent::tearDown();
    }

    public function test_v3_login_verifies_and_rehashes_password(): void
    {
        $this->createJobSeeker('v3-user', 'v3@example.com', $this->vectors['v3_hash']);

        $response = $this->postJson('/auth/job-seeker/login', [
            'email' => 'v3@example.com',
            'password' => $this->vectors['password'],
        ]);

        $response->assertOk()->assertJson(['status' => 'ok']);

        $user = JobSeeker::query()->findOrFail('v3-user');
        $this->assertTrue(Hash::check($this->vectors['password'], (string) $user->PasswordHash));
        $this->assertNotSame($this->vectors['v3_hash'], (string) $user->PasswordHash);
        $this->assertNotSame('stamp-v3-user', (string) $user->SecurityStamp);
    }

    public function test_f0_login_verifies_and_rehashes_password(): void
    {
        $this->createJobSeeker('f0-user', 'f0@example.com', $this->vectors['f0_hash']);

        $response = $this->postJson('/auth/job-seeker/login', [
            'email' => 'f0@example.com',
            'password' => $this->vectors['password'],
        ]);

        $response->assertOk()->assertJson(['status' => 'ok']);

        $user = JobSeeker::query()->findOrFail('f0-user');
        $this->assertTrue(Hash::check($this->vectors['password'], (string) $user->PasswordHash));
        $this->assertNotSame($this->vectors['f0_hash'], (string) $user->PasswordHash);
        $this->assertNotSame('stamp-f0-user', (string) $user->SecurityStamp);
    }

    public function test_verifier_matches_all_genuine_dotnet_vectors(): void
    {
        // Two independent hash pairs per format, generated by real ASP.NET Core
        // Identity (see the fixture's _provenance) — proves compatibility, not just
        // self-consistency.
        $hasher = new LegacyPasswordHasher;

        foreach (['v3_hash', 'v3_hash_2', 'f0_hash', 'f0_hash_2'] as $key) {
            $this->assertSame(
                LegacyHashVerificationResult::VerifiedNeedsRehash,
                $hasher->verify($this->vectors[$key], $this->vectors['password']),
                "correct password must verify for {$key}",
            );
            $this->assertSame(
                LegacyHashVerificationResult::Failed,
                $hasher->verify($this->vectors[$key], $this->vectors['wrong_password']),
                "wrong password must fail for {$key}",
            );
        }
    }

    public function test_wrong_password_fails_for_known_hash_format(): void
    {
        $this->createJobSeeker('wrong-user', 'wrong@example.com', $this->vectors['v3_hash']);

        $response = $this->postJson('/auth/job-seeker/login', [
            'email' => 'wrong@example.com',
            'password' => $this->vectors['wrong_password'],
        ]);

        $response->assertStatus(422)->assertJson(['status' => 'invalid_credentials']);

        $user = JobSeeker::query()->findOrFail('wrong-user');
        $this->assertSame($this->vectors['v3_hash'], (string) $user->PasswordHash);
    }

    public function test_unrecognized_hash_routes_to_force_reset(): void
    {
        $this->createJobSeeker('reset-user', 'reset@example.com', 'not-base64-hash');

        $response = $this->postJson('/auth/job-seeker/login', [
            'email' => 'reset@example.com',
            'password' => $this->vectors['password'],
        ]);

        $response->assertStatus(409)->assertJson(['status' => 'force_reset_required']);
    }

    public function test_register_then_verify_email_flow(): void
    {
        $response = $this->postJson('/auth/job-seeker/register', [
            'email' => 'new-user@example.com',
            'username' => 'new-user@example.com',
            'password' => 'NewPassword!123',
            'password_confirmation' => 'NewPassword!123',
        ]);

        $response->assertStatus(201);

        $id = (string) $response->json('id');
        $guid = (string) $response->json('verificationGuid');

        $created = JobSeeker::query()->findOrFail($id);
        $this->assertSame('NEW-USER@EXAMPLE.COM', $created->NormalizedEmail);
        $this->assertSame('NEW-USER@EXAMPLE.COM', $created->NormalizedUserName);
        $this->assertFalse((bool) $created->EmailConfirmed);
        $this->assertSame(AccountStatus::Pending, $created->AccountStatus);

        $verify = $this->getJson("/auth/job-seeker/verify/{$id}/{$guid}");
        $verify->assertOk()->assertJson(['status' => 'verified']);

        $verified = JobSeeker::query()->findOrFail($id);
        $this->assertTrue((bool) $verified->EmailConfirmed);
        $this->assertSame(AccountStatus::Active, $verified->AccountStatus);
        $this->assertNull($verified->VerificationGuid);
    }

    public function test_email_only_password_reset_flow(): void
    {
        $this->createJobSeeker('pwd-user', 'pwd@example.com', $this->vectors['v3_hash'], false, AccountStatus::Pending->value);

        $forgot = $this->postJson('/auth/job-seeker/forgot-password', ['email' => 'pwd@example.com']);
        $forgot->assertOk()->assertJson(['status' => 'reset_link_queued']);

        $user = JobSeeker::query()->findOrFail('pwd-user');
        $oldStamp = (string) $user->SecurityStamp;
        $token = Password::broker('job_seekers')->createToken($user);

        $reset = $this->postJson('/auth/job-seeker/reset-password', [
            'email' => 'pwd@example.com',
            'token' => $token,
            'password' => 'BrandNew!456',
            'password_confirmation' => 'BrandNew!456',
        ]);

        $reset->assertOk()->assertJson(['status' => 'password_reset']);

        $updated = JobSeeker::query()->findOrFail('pwd-user');
        $this->assertTrue(Hash::check('BrandNew!456', (string) $updated->PasswordHash));
        $this->assertNotSame($oldStamp, (string) $updated->SecurityStamp);
        $this->assertSame('PWD@EXAMPLE.COM', $updated->NormalizedEmail);
        $this->assertSame('PWD@EXAMPLE.COM', $updated->NormalizedUserName);
        $this->assertTrue((bool) $updated->EmailConfirmed);
        $this->assertSame(AccountStatus::Active, $updated->AccountStatus);
    }

    public function test_login_route_returns_429_on_sixth_rapid_attempt(): void
    {
        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/login', [
                'email' => 'throttle-login@example.com',
                'password' => 'wrong',
            ])->assertStatus(422);
        }

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'throttle-login@example.com',
            'password' => 'wrong',
        ])->assertStatus(429);
    }

    public function test_register_forgot_and_reset_routes_are_throttled_with_429(): void
    {
        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/register', [
                'email' => 'throttle-register@example.com',
                'username' => 'throttle-register@example.com',
                'password' => 'StrongPass!123',
                'password_confirmation' => 'StrongPass!123',
            ]);
        }

        $this->postJson('/auth/job-seeker/register', [
            'email' => 'throttle-register@example.com',
            'username' => 'throttle-register@example.com',
            'password' => 'StrongPass!123',
            'password_confirmation' => 'StrongPass!123',
        ])->assertStatus(429);

        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/forgot-password', [
                'email' => 'throttle-forgot@example.com',
            ]);
        }

        $this->postJson('/auth/job-seeker/forgot-password', [
            'email' => 'throttle-forgot@example.com',
        ])->assertStatus(429);

        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/reset-password', [
                'email' => 'throttle-reset@example.com',
                'token' => 'token-one',
                'password' => 'StrongPass!123',
                'password_confirmation' => 'StrongPass!123',
            ]);
        }

        $this->postJson('/auth/job-seeker/reset-password', [
            'email' => 'throttle-reset@example.com',
            'token' => 'token-one',
            'password' => 'StrongPass!123',
            'password_confirmation' => 'StrongPass!123',
        ])->assertStatus(429);
    }

    public function test_access_failed_count_increments_on_failed_password_and_clears_on_success(): void
    {
        $this->createJobSeeker('lock-user', 'lock-user@example.com', $this->vectors['v3_hash'], lockoutEnabled: true);

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'lock-user@example.com',
            'password' => $this->vectors['wrong_password'],
        ])->assertStatus(422);

        $afterFailure = JobSeeker::query()->findOrFail('lock-user');
        $this->assertSame(1, (int) $afterFailure->AccessFailedCount);

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'lock-user@example.com',
            'password' => $this->vectors['password'],
        ])->assertOk()->assertJson(['status' => 'ok']);

        $afterSuccess = JobSeeker::query()->findOrFail('lock-user');
        $this->assertSame(0, (int) $afterSuccess->AccessFailedCount);
        $this->assertNull($afterSuccess->LockoutEnd);
    }

    public function test_locked_account_is_refused_even_with_correct_password(): void
    {
        config()->set('auth.job_seeker_lockout.max_failed_attempts', 5);
        config()->set('auth.job_seeker_lockout.minutes', 30);
        config()->set('auth.job_seeker_rate_limits.login.per_minute', 50);

        $this->createJobSeeker('locked-user', 'locked@example.com', $this->vectors['v3_hash'], lockoutEnabled: true);

        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/login', [
                'email' => 'locked@example.com',
                'password' => $this->vectors['wrong_password'],
            ])->assertStatus(422);
        }

        $locked = JobSeeker::query()->findOrFail('locked-user');
        $this->assertSame(5, (int) $locked->AccessFailedCount);
        $this->assertNotNull($locked->LockoutEnd);

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'locked@example.com',
            'password' => $this->vectors['password'],
        ])->assertStatus(422)->assertJson(['status' => 'invalid_credentials']);
    }

    public function test_lock_expires_after_lockout_end_and_login_succeeds(): void
    {
        Carbon::setTestNow('2026-08-04 10:00:00');

        $this->createJobSeeker('expired-lock', 'expired-lock@example.com', $this->vectors['v3_hash'], lockoutEnabled: true);
        DB::table('AspNetUsers')->where('Id', 'expired-lock')->update([
            'AccessFailedCount' => 5,
            'LockoutEnd' => Carbon::now()->subMinute(),
            'DateLocked' => Carbon::now()->subMinutes(31),
        ]);

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'expired-lock@example.com',
            'password' => $this->vectors['password'],
        ])->assertOk()->assertJson(['status' => 'ok']);

        $user = JobSeeker::query()->findOrFail('expired-lock');
        $this->assertSame(0, (int) $user->AccessFailedCount);
        $this->assertNull($user->LockoutEnd);
        $this->assertNull($user->DateLocked);
    }

    public function test_lockout_disabled_users_are_never_locked(): void
    {
        config()->set('auth.job_seeker_rate_limits.login.per_minute', 50);

        $this->createJobSeeker('no-lock', 'no-lock@example.com', $this->vectors['v3_hash'], lockoutEnabled: false);

        for ($attempt = 1; $attempt <= 5; $attempt++) {
            $this->postJson('/auth/job-seeker/login', [
                'email' => 'no-lock@example.com',
                'password' => $this->vectors['wrong_password'],
            ])->assertStatus(422);
        }

        $user = JobSeeker::query()->findOrFail('no-lock');
        $this->assertSame(0, (int) $user->AccessFailedCount);
        $this->assertNull($user->LockoutEnd);

        $this->postJson('/auth/job-seeker/login', [
            'email' => 'no-lock@example.com',
            'password' => $this->vectors['password'],
        ])->assertOk()->assertJson(['status' => 'ok']);
    }

    private function createFixture(): void
    {
        $this->dropFixture();

        Schema::create('AspNetUsers', function (Blueprint $table): void {
            $table->string('Id')->primary();
            $table->string('UserName')->nullable();
            $table->string('NormalizedUserName')->nullable();
            $table->string('Email')->nullable();
            $table->string('NormalizedEmail')->nullable();
            $table->boolean('EmailConfirmed')->default(false);
            $table->string('PasswordHash')->nullable();
            $table->string('SecurityStamp')->nullable();
            $table->boolean('PhoneNumberConfirmed')->default(false);
            $table->boolean('TwoFactorEnabled')->default(false);
            $table->boolean('LockoutEnabled')->default(false);
            $table->dateTime('LockoutEnd')->nullable();
            $table->integer('AccessFailedCount')->default(0);
            $table->smallInteger('AccountStatus')->default(AccountStatus::Pending->value);
            $table->uuid('VerificationGuid')->nullable();
            $table->dateTime('DateRegistered')->nullable();
            $table->dateTime('LastModified')->nullable();
            $table->dateTime('LastLogon')->nullable();
            $table->dateTime('DateLocked')->nullable();
        });

        Schema::create('password_reset_tokens', function (Blueprint $table): void {
            $table->string('email')->primary();
            $table->string('token');
            $table->timestamp('created_at')->nullable();
        });
    }

    private function dropFixture(): void
    {
        Schema::dropIfExists('password_reset_tokens');
        Schema::dropIfExists('AspNetUsers');
    }

    private function createJobSeeker(
        string $id,
        string $email,
        string $passwordHash,
        bool $emailConfirmed = true,
        int $status = 1,
        bool $lockoutEnabled = false,
    ): void
    {
        DB::table('AspNetUsers')->insert([
            'Id' => $id,
            'UserName' => $email,
            'NormalizedUserName' => mb_strtoupper($email, 'UTF-8'),
            'Email' => $email,
            'NormalizedEmail' => mb_strtoupper($email, 'UTF-8'),
            'EmailConfirmed' => $emailConfirmed,
            'PasswordHash' => $passwordHash,
            'SecurityStamp' => 'stamp-'.$id,
            'LockoutEnabled' => $lockoutEnabled,
            'AccessFailedCount' => 0,
            'LockoutEnd' => null,
            'AccountStatus' => $status,
            'VerificationGuid' => null,
            'DateRegistered' => now(),
            'LastModified' => now(),
        ]);
    }
}
