using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

namespace WorkBC.Data.Migrations
{
    public partial class AddTable_Country : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            //migrationBuilder.AlterColumn<string>(
            //    name: "Name",
            //    table: "AspNetUserTokens",
            //    maxLength: 128,
            //    nullable: false,
            //    oldClrType: typeof(string));

            //migrationBuilder.AlterColumn<string>(
            //    name: "LoginProvider",
            //    table: "AspNetUserTokens",
            //    maxLength: 128,
            //    nullable: false,
            //    oldClrType: typeof(string));

            //migrationBuilder.AlterColumn<string>(
            //    name: "ProviderKey",
            //    table: "AspNetUserLogins",
            //    maxLength: 128,
            //    nullable: false,
            //    oldClrType: typeof(string));

            //migrationBuilder.AlterColumn<string>(
            //    name: "LoginProvider",
            //    table: "AspNetUserLogins",
            //    maxLength: 128,
            //    nullable: false,
            //    oldClrType: typeof(string));

            migrationBuilder.CreateTable(
                name: "Country",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn),
                    Name = table.Column<string>(nullable: true),
                    CountryTwoLetterCode = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Country", x => x.Id);
                });

            var countries = new[] {
                new[] { "Canada", "CA" },
                new[] { "USA", "US" },
                new[] { "Afghanistan", "AF" },
                new[] { "Albania", "AL" },
                new[] { "Algeria", "DZ" },
                new[] { "AmericanSamoa", "AS" },
                new[] { "Andorra", "AD" },
                new[] { "Angola", "AO" },
                new[] { "Anguilla", "AI" },
                new[] { "Antarctica", "AQ" },
                new[] { "AntiguaAndBarbuda", "AG" },
                new[] { "Argentina", "AR" },
                new[] { "Armenia", "AM" },
                new[] { "Aruba", "AW" },
                new[] { "Australia", "AU" },
                new[] { "Austria", "AT" },
                new[] { "Azerbaijan", "AZ" },
                new[] { "Bahamas", "BS" },
                new[] { "Bahrain", "BH" },
                new[] { "Bangladesh", "BD" },
                new[] { "Barbados", "BB" },
                new[] { "Belarus", "BY" },
                new[] { "Belgium", "BE" },
                new[] { "Belize", "BZ" },
                new[] { "Benin", "BJ" },
                new[] { "Bermuda", "BM" },
                new[] { "Bhutan", "BT" },
                new[] { "Bolivia", "BO" },
                new[] { "Bosnia-Herzegovinia", "BA" },
                new[] { "Botswana", "BW" },
                new[] { "BouvetIsland", "BV" },
                new[] { "Brazil", "BR" },
                new[] { "BritishIndianOceanTerritory", "IO" },
                new[] { "BruneiDarussalam", "BN" },
                new[] { "Bulgaria", "BG" },
                new[] { "BurkinaFaso", "BF" },
                new[] { "Burundi", "BI" },
                new[] { "Cambodia", "KH" },
                new[] { "Cameroon", "CM" },
                new[] { "CapeVerde", "CV" },
                new[] { "CaymanIslands", "KY" },
                new[] { "CentralAfricanRepublic", "CF" },
                new[] { "Chad", "TD" },
                new[] { "Chile", "CL" },
                new[] { "China", "CN" },
                new[] { "ChristmasIsland", "CX" },
                new[] { "Cocos_Keeling_Islands", "CC" },
                new[] { "Colombia", "CO" },
                new[] { "Comoros", "KM" },
                new[] { "Congo", "CG" },
                new[] { "CongoDemRepublic", "CD" },
                new[] { "CookIslands", "CK" },
                new[] { "CostaRica", "CR" },
                new[] { "Croatia", "HR" },
                new[] { "Cuba", "CU" },
                new[] { "Cyprus", "CY" },
                new[] { "CzechRepublic", "CZ" },
                new[] { "Denmark", "DK" },
                new[] { "Djibouti", "DJ" },
                new[] { "Dominica", "DM" },
                new[] { "EastTimor", "TL" },
                new[] { "Ecuador", "EC" },
                new[] { "Egypt", "EG" },
                new[] { "ElSalvador", "SV" },
                new[] { "EquatorialGuinea", "GQ" },
                new[] { "Eritrea", "ER" },
                new[] { "Estonia", "EE" },
                new[] { "Ethiopia", "ET" },
                new[] { "FalklandIslands_Malvinas", "FK" },
                new[] { "FaroeIslands", "FO" },
                new[] { "Fiji", "FJ" },
                new[] { "Finland", "FI" },
                new[] { "France", "FR" },
                new[] { "FrenchGuiana", "GF" },
                new[] { "FrenchPolynesia", "PF" },
                new[] { "FrenchSouthernTerritories", "TF" },
                new[] { "Gabon", "GA" },
                new[] { "Gambia", "GM" },
                new[] { "Georgia", "GE" },
                new[] { "Germany", "DE" },
                new[] { "Ghana", "GH" },
                new[] { "Gibraltar", "GI" },
                new[] { "Greece", "GR" },
                new[] { "Greenland", "GL" },
                new[] { "Grenada", "GD" },
                new[] { "Guadeloupe", "GP" },
                new[] { "Guam", "GU" },
                new[] { "Guatemala", "GT" },
                new[] { "GuernseyAndAlderney", "GG" },
                new[] { "Guinea", "GN" },
                new[] { "Guinea-Bissau", "GW" },
                new[] { "Guyana", "GY" },
                new[] { "Haiti", "HT" },
                new[] { "HeardandMcDonaldIslands", "HM" },
                new[] { "Honduras", "HN" },
                new[] { "HongKong", "HK" },
                new[] { "Hungary", "HU" },
                new[] { "Iceland", "IS" },
                new[] { "India", "IN" },
                new[] { "Indonesia", "ID" },
                new[] { "Iran", "IR" },
                new[] { "Iraq", "IQ" },
                new[] { "Ireland", "IE" },
                new[] { "IslandOfMan", "IM" },
                new[] { "Israel", "IL" },
                new[] { "Italy", "IT" },
                new[] { "IvoryCoast", "CI" },
                new[] { "Jamaica", "JM" },
                new[] { "Japan", "JP" },
                new[] { "Jersey", "JE" },
                new[] { "Jordan", "JO" },
                new[] { "Kazakhstan", "KZ" },
                new[] { "Kenya", "KE" },
                new[] { "Kiribati", "KI" },
                new[] { "Korea_DemocraticRepublicOf", "KP" },
                new[] { "Korea_RepublicOf", "KR" },
                new[] { "Kosovo", "" },
                new[] { "Kuwait", "KW" },
                new[] { "KyrgyzRepublic", "KG" },
                new[] { "Laos", "LA" },
                new[] { "Latvia", "LV" },
                new[] { "Lebanon", "LB" },
                new[] { "Lesotho", "LS" },
                new[] { "Liberia", "LR" },
                new[] { "Libya", "LY" },
                new[] { "Liechtenstein", "LI" },
                new[] { "Lithuania", "LT" },
                new[] { "Luxembourg", "LU" },
                new[] { "Macau", "MO" },
                new[] { "Macedonia", "MK" },
                new[] { "Madagascar", "MG" },
                new[] { "Malawi", "MW" },
                new[] { "Malaysia", "MY" },
                new[] { "Maldives", "MV" },
                new[] { "Mali", "ML" },
                new[] { "Malta", "MT" },
                new[] { "MarshallIslands", "MH" },
                new[] { "Martinique", "MQ" },
                new[] { "Mauritania", "MR" },
                new[] { "Mauritius", "MU" },
                new[] { "Mayotte", "YT" },
                new[] { "Mexico", "MX" },
                new[] { "Micronesia", "FM" },
                new[] { "Moldavia", "MD" },
                new[] { "Monaco", "MC" },
                new[] { "Mongolia", "MN" },
                new[] { "Montenegro", "ME" },
                new[] { "Montserrat", "MS" },
                new[] { "Morocco", "MA" },
                new[] { "Mozambique", "MZ" },
                new[] { "Myanmar", "MM" },
                new[] { "Namibia", "NA" },
                new[] { "Nauru", "NR" },
                new[] { "Nepal", "NP" },
                new[] { "Netherlands", "NL" },
                new[] { "NetherlandsAntilles", "AN" },
                new[] { "NewCaledonia", "NC" },
                new[] { "NewZealand", "NZ" },
                new[] { "Nicaragua", "NI" },
                new[] { "Niger", "NE" },
                new[] { "Nigeria", "NG" },
                new[] { "Niue", "NU" },
                new[] { "NorfolkIsland", "NF" },
                new[] { "NorthernMarianaIslands", "MP" },
                new[] { "Norway", "NO" },
                new[] { "Oman", "OM" },
                new[] { "Pakistan", "PK" },
                new[] { "Palau", "PW" },
                new[] { "PalestinianTerritory", "PS" },
                new[] { "Panama", "PA" },
                new[] { "Papua-NewGuinea", "PG" },
                new[] { "Paraguay", "PY" },
                new[] { "Peru", "PE" },
                new[] { "Philippines", "PH" },
                new[] { "Pitcairn", "PN" },
                new[] { "Poland", "PL" },
                new[] { "Portugal", "PT" },
                new[] { "PuertoRico", "PR" },
                new[] { "Qatar", "QA" },
                new[] { "ReUnion", "RE" },
                new[] { "RepublicOfDominica", "DO" },
                new[] { "Romania", "RO" },
                new[] { "RussianFederation", "RU" },
                new[] { "Rwanda", "RW" },
                new[] { "SaintBarthelemy", "BL" },
                new[] { "SaintHelena", "SH" },
                new[] { "SaintKittsAndNevis", "KN" },
                new[] { "SaintLucia", "LC" },
                new[] { "SaintMartin", "MF" },
                new[] { "SaintPierreAndMiquelon", "PM" },
                new[] { "SaintVincentAndTheGrenadines", "VC" },
                new[] { "Samoa", "WS" },
                new[] { "SanMarino", "SM" },
                new[] { "SaoTomeAndPrincipe", "ST" },
                new[] { "SaudiArabia", "SA" },
                new[] { "Senegal", "SN" },
                new[] { "Serbia", "RS" },
                new[] { "Seychelles", "SC" },
                new[] { "SierraLeone", "SL" },
                new[] { "Singapore", "SG" },
                new[] { "Slovakia", "SK" },
                new[] { "Slovenia", "SI" },
                new[] { "SolomonIslands", "SB" },
                new[] { "Somalia", "SO" },
                new[] { "SouthAfrica", "ZA" },
                new[] { "SouthGeorgiaSouthSandwichIslands", "GS" },
                new[] { "Spain", "ES" },
                new[] { "SriLanka", "LK" },
                new[] { "Sudan", "SD" },
                new[] { "Suriname", "SR" },
                new[] { "SvalbardAndJanMayenIslands", "SJ" },
                new[] { "Swaziland", "SZ" },
                new[] { "Sweden", "SE" },
                new[] { "Switzerland", "CH" },
                new[] { "SyrianArabRepublic", "SY" },
                new[] { "Taiwan", "TW" },
                new[] { "Tajikistan", "TJ" },
                new[] { "Tanzania", "TZ" },
                new[] { "Thailand", "TH" },
                new[] { "Togo", "TG" },
                new[] { "Tokelau", "TK" },
                new[] { "Tonga", "TO" },
                new[] { "TrinidadAndTobago", "TT" },
                new[] { "Tunisia", "TN" },
                new[] { "Turkey", "TR" },
                new[] { "Turkmenistan", "TM" },
                new[] { "TurksAndCaicosIslands", "TC" },
                new[] { "Tuvalu", "TV" },
                new[] { "Uganda", "UG" },
                new[] { "Ukraine", "UA" },
                new[] { "UnitedArabEmirates", "AE" },
                new[] { "UnitedKingdom", "GB" },
                new[] { "UnitedStatesMinorOutlyingIslands", "UM" },
                new[] { "Uruguay", "UY" },
                new[] { "Uzbekistan", "UZ" },
                new[] { "Vanuatu", "VU" },
                new[] { "HolySee", "VA" },
                new[] { "Venezuela", "VE" },
                new[] { "Vietnam", "VN" },
                new[] { "VirginIslands_British", "VG" },
                new[] { "VirginIslands_US", "VI" },
                new[] { "WallisandFutunaIslands", "WF" },
                new[] { "WesternSahara", "EH" },
                new[] { "Yemen", "YE" },
                new[] { "Zambia", "ZM" },
                new[] { "Zimbabwe", "ZW" }
            };

            foreach (var country in countries)
            {
                migrationBuilder.InsertData(
                    table: "Country",
                    columns: new[] { "Name", "CountryTwoLetterCode" },
                    values: new[] { country[0], country[1] });
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Country");

            //migrationBuilder.AlterColumn<string>(
            //    name: "Name",
            //    table: "AspNetUserTokens",
            //    nullable: false,
            //    oldClrType: typeof(string),
            //    oldMaxLength: 128);

            //migrationBuilder.AlterColumn<string>(
            //    name: "LoginProvider",
            //    table: "AspNetUserTokens",
            //    nullable: false,
            //    oldClrType: typeof(string),
            //    oldMaxLength: 128);

            //migrationBuilder.AlterColumn<string>(
            //    name: "ProviderKey",
            //    table: "AspNetUserLogins",
            //    nullable: false,
            //    oldClrType: typeof(string),
            //    oldMaxLength: 128);

            //migrationBuilder.AlterColumn<string>(
            //    name: "LoginProvider",
            //    table: "AspNetUserLogins",
            //    nullable: false,
            //    oldClrType: typeof(string),
            //    oldMaxLength: 128);
        }
    }
}
