#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM src_jb-dotnet-build AS dotnet-build
WORKDIR /src
COPY ["WorkBC.Tests/", "WorkBC.Tests/"]
RUN dotnet restore "WorkBC.Tests/WorkBC.Tests.csproj"
RUN dotnet build "WorkBC.Tests/WorkBC.Tests.csproj" -c Release --no-restore --no-dependencies
ENV ConnectionStrings__ElasticSearchServer "http://elasticsearch:9200"
ENTRYPOINT ["dotnet", "test", "WorkBC.Tests/WorkBC.Tests.csproj", "-c", "Release", "--no-restore", "--no-build"]
