version: '3.4'
services:
    jb-dotnet-build:
        container_name: jb-dotnet-build
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Shared/Dockerfile
    web:
        container_name: web
        build:
            context: .
            dockerfile: ./WorkBC.Web/Dockerfile
        ports:
            - "8081:8081"
        environment:
            - ASPNETCORE_URLS=http://*:8081
            - ASPNETCORE_ENVIRONMENT=Development
        env_file:
            - .env
    admin:
        build:
            context: .
            dockerfile: ./WorkBC.Admin/Dockerfile
        ports:
            - "8080:8080"
        environment:
            - ASPNETCORE_URLS=http://*:8080
            - ASPNETCORE_ENVIRONMENT=Development
        env_file:
            - .env
    importers-wanted:
        container_name: importers-wanted
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Importers.Wanted/Dockerfile
        env_file:
            - .env
    importers-federal:
        container_name: importers-federal
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Importers.Federal/Dockerfile
        env_file:
            - .env
    indexers-federal:
        container_name: indexers-federal
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Indexers.Federal/Dockerfile
        env_file:
            - .env
    indexers-wanted:
        container_name: indexers-wanted
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Indexers.Wanted/Dockerfile
        env_file:
            - .env
    notifications-job-alerts:
        container_name: notifications-job-alerts
        scale: 0
        build:
            context: .
            dockerfile: ./WorkBC.Notifications.JobAlerts/Dockerfile
        env_file:
            - .env
    migration-runner:
        container_name: migration-runner
        scale: 0
        build:
            context: .
            dockerfile: ./EFMigrationRunner/Dockerfile
        env_file:
            - .env
