version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.8
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
  kibana:
    image: kibana:7.17.8
    ports:
      - 5601:5601
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    stdin_open: true
    tty: true
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "18^fh4M08aB@"
    volumes:
      - mssql_data:/var/opt/mssql/data
volumes:
  mssql_data:
