version: '3'
services:
  web:
    volumes:
      - ./WorkBC.Web/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  admin:
    volumes:
      - ./WorkBC.Admin/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  importers-wanted:
    volumes:
      - ./WorkBC.Importers.Wanted/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  importers-federal:
    volumes:
      - ./WorkBC.Importers.Federal/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  indexers-federal:
    volumes:
      - ./WorkBC.Indexers.Federal/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  indexers-wanted:
    volumes:
      - ./WorkBC.Indexers.Wanted/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
  notifications-job-alerts:
    volumes:
      - ./WorkBC.Notifications.JobAlerts/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  migration-runner:
    volumes:
      - ./EFMigrationRunner/appsettings.linux.json:/app/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  dotnet-cli:
    volumes:
      - ./WorkBC.Importers.Wanted/appsettings.linux.json:/app/workbc-importers-wanted/appsettings.json
      - ./WorkBC.Importers.Federal/appsettings.linux.json:/app/workbc-importers-federal/appsettings.json
      - ./WorkBC.Indexers.Wanted/appsettings.linux.json:/app/workbc-indexers-wanted/appsettings.json
      - ./WorkBC.Indexers.Federal/appsettings.linux.json:/app/workbc-indexers-federal/appsettings.json
      - ./WorkBC.Notifications.JobAlerts/appsettings.linux.json:/app/workbc-notifications-jobalerts/appsettings.json
      - ./EFMigrationRunner/appsettings.linux.json:/app/efmigrationrunner/appsettings.json
    depends_on:
      postgres:
        condition: service_healthy
  elasticsearch:
    image: elasticsearch:7.17.8
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 30s
      timeout: 10s
      retries: 50
  kibana:
    image: kibana:7.17.8
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
  postgres:
    image: postgres:15.5-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: workbc
      POSTGRES_PASSWORD: workbc
    healthcheck:
      test: "pg_isready --dbname=jobboard --username=workbc && psql --username=workbc --list jobboard"
      timeout: 5s
      retries: 20
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./scripts/postgres-init:/docker-entrypoint-initdb.d"
volumes:
  pg_data:
  es_data: