version: '3'
name: workbc-jb-local
services:
  web:
    depends_on:
      - postgres
  admin:
    depends_on:
      - postgres
  importers-wanted:
    depends_on:
      - postgres
  importers-federal:
    depends_on:
      - postgres
  indexers-federal:
    depends_on:
      - postgres
  indexers-wanted:
    depends_on:
      - postgres
  notifications-job-alerts:
    depends_on:
      - postgres
  migration-runner:
    depends_on:
      - postgres
  elasticsearch:
    image: elasticsearch:7.17.8
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
  kibana:
    image: kibana:7.17.8
    ports:
      - 5601:5601
  postgres:
    image: postgres:15.5-bookworm
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: jobboard
      POSTGRES_USER: workbc
      POSTGRES_PASSWORD: workbc
    healthcheck:
      test: "pg_isready --dbname=jobboard --username=workbc && psql --username=workbc --list jobboard"
      timeout: 5s
      retries: 20
    volumes:
      - "pg_data:/var/lib/postgresql/data"
      - "./scripts/postgres-init:/docker-entrypoint-initdb.d"
  ssot:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://workbc:workbc@postgres:5432/ssot
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: ssot_readonly
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    depends_on:
      - postgres
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8888:8080"
    environment:
      API_URL: http://localhost:3000/
    depends_on:
      - ssot
volumes:
  pg_data:
  es_data: